const express = require("express");
const router = express.Router();

const movies = [
  {
    id: 1,
    title: "Avengers: Endgame",
    language: "English",
    genre: "Action",
    seatsAvailable: 50,
    image: "avengers.jpg",
    likes: 1200,
    rating: 4.8,
    reviews: ["Awesome movie!", "Great action scenes!", "Loved the ending!"],
  },
  {
    id: 2,
    title: "Inception",
    language: "English",
    genre: "Sci-Fi",
    seatsAvailable: 30,
    image: "inception.jpg",
    likes: 900,
    rating: 4.7,
    reviews: ["Mind-blowing!", "Nolan is a genius!", "A masterpiece."],
  },
  {
    id: 3,
    title: "Interstellar",
    language: "English",
    genre: "Sci-Fi, Drama",
    seatsAvailable: 100,
    image: "interstellar.jpg",
    likes: 900,
    rating: 4.9,
    reviews: [
      "Mind-blowing!",
      "Nolan is a genius!",
      "The ending is epic, cannot believe what I was watching!",
    ],
  },
  {
    id: 4,
    title: "The Shawshank Redemption",
    language: "English",
    genre: "Drama",
    seatsAvailable: 34,
    image: "shawshank.jpg",
    likes: 800,
    rating: 4.9,
    reviews: ["Oscar worthy", "Unbelievable ending!", "Genius film."],
  },
  {
    id: 5,
    title: "Rocky",
    language: "English",
    genre: "Sports",
    seatsAvailable: 50,
    image: "rocky.jpg",
    likes: 900,
    rating: 4.7,
    reviews: ["Inspiring", "A masterpiece."],
  },
  {
    id: 6,
    title: "Raging Bull",
    language: "English",
    genre: "Sports, Biography",
    seatsAvailable: 30,
    image: "ragingbull.jpg",
    likes: 800,
    rating: 4.7,
    reviews: ["Martin Scorsese is a genius!", "A masterpiece."],
  },
  {
    id: 7,
    title: "2001: A Space Odyssey",
    language: "English",
    genre: "Sci-Fi, Thriller",
    seatsAvailable: 25,
    image: "odyssey.jpg",
    likes: 955,
    rating: 4.9,
    reviews: ["Mind-blowing!", "Kubrick is a genius!", "A masterpiece."],
  },
  {
    id: 8,
    title: "Oppenheimer",
    language: "English",
    genre: "Biography, History",
    seatsAvailable: 50,
    image: "cylian.jpg",
    likes: 800,
    rating: 4.9,
    reviews: ["Greatest film of this decade", "Nolan has delivered once again"],
  },
  {
    id: 9,
    title: "The Godfather",
    language: "English",
    genre: "Drama, Crime",
    seatsAvailable: 30,
    image: "godfather.jpg",
    likes: 800,
    rating: 5.0,
    reviews: ["The greatest movie of this generation"],
  },
  {
    id: 10,
    title: "3 Idiots",
    language: "Hindi",
    genre: "Comedy, Drama",
    seatsAvailable: 45,
    image: "3idiots.jpg",
    likes: 2200,
    rating: 4.9,
    reviews: ["Incredibly inspiring!", "Best Bollywood movie ever!"],
  },
  {
    id: 11,
    title: "Gully Boy",
    language: "Hindi",
    genre: "Musical, Drama",
    seatsAvailable: 40,
    image: "gullyboy.jpg",
    likes: 1800,
    rating: 4.7,
    reviews: ["Rap revolution in India!", "Loved the performances!"],
  },
  {
    id: 12,
    title: "Your Name",
    language: "Japanese",
    genre: "Anime, Romance",
    seatsAvailable: 30,
    image: "yourname.jpg",
    likes: 3000,
    rating: 4.9,
    reviews: ["Beautiful animation!", "Heart-touching story!", "Loved it!"],
  },
  {
    id: 13,
    title: "One Piece",
    language: "Japanese",
    genre: "Anime, Adventure",
    seatsAvailable: 30,
    image: "onepiece.jpg",
    likes: 3200,
    rating: 5.0,
    reviews: ["Masterpiece by Miyazaki!", "Unforgettable experience!"],
  },
  {
    id: 14,
    title: "Black Panther",
    language: "English",
    genre: "ACtion, Drama",
    seatsAvailable: 50,
    image: "blackpanther.jpg",
    likes: 800,
    rating: 4.9,
    reviews: ["Intense Action and Directography", "One of Chadwick's Finest"],
  },
];

router.get("/", (req, res) => {
  const language = req.query.language;
  if (language) {
    const filteredMovies = movies.filter((movie) => movie.language.toLowerCase() === language.toLowerCase());
    return res.json(filteredMovies);
  }
  res.json(movies);
});

module.exports = router;
